### ISSUE TITLE
Applying JSON Schema to JSON Gen

### ISSUE THREAD

**Issue by ChilliPommes** [ChilliPommes/ChillipommesGenerator#1]
### Description

To handle the generated JSON correctly, we need to implement a standard.
For this we will use the JSON Schema : https://json-schema.org/draft/2020-12/schema

With This Standard we will generate the JSON

### TODOs

- [x] Implement Base For Schema
- [x] Add JSON Property Tags to Fields
- [x] Apply Schema Strucutres into structs
- [x] Apply all correct namings

**Comment by ChilliPommes** [comment]
Implementation is done !

**Comment by ChilliPommes** [comment]
- [x] Refactor Interface Parser
- [x] Automatic Testing
